export const ADD_ADMIN = 'ADD_ADMINISTRATOR';
export const EDIT_ADMIN = 'EDIT_ADMINISTRATOR';
export const REMOVE_ADMIN = 'REMOVE_ADMINISTRATOR';
export const ADMINS = 'LIST_ADMINISTRATORS';
export const FETCH_ADMINS_FAILED = 'FETCH_ADMINSTRATORS_FAILED';